; PlatformIO Project Configuration File
;
; Para o ESP32-CAM (AI-Thinker) com framework Arduino

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
lib_deps = ESP32QRCodeReader
; Velocidade do monitor serial
monitor_speed = 115200

monitor_rts=0
monitor_dtr=0

; Velocidade de upload (pode ser reduzida se houver falhas)
upload_speed = 921600

; Habilitar PSRAM (a placa possui 4MB de PSRAM)
board_build.psram = enable

; Opcionais: frequência da CPU e modo flash
; board_build.f_cpu = 240000000L
; board_build.flash_mode = dio

upload_port = /dev/ttyUSB0